"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
var attributes = require("./lib/attributes");
var base = require("./lib/base");
var display = require("./lib/display");
var graphics = require("./lib/graphics");
var image = require("./lib/image");
var library = require("./lib/library");
var materials = require("./lib/materials");
var parsers = require("./lib/parsers");
var partition = require("./lib/partition");
var textures = require("./lib/textures");
var GL_AttributesBuffer_1 = require("@awayjs/stage/lib/attributes/GL_AttributesBuffer");
var Stage_1 = require("@awayjs/stage/lib/base/Stage");
var GL_BitmapImage2D_1 = require("@awayjs/stage/lib/image/GL_BitmapImage2D");
var GL_BitmapImageCube_1 = require("@awayjs/stage/lib/image/GL_BitmapImageCube");
var GL_RenderImage2D_1 = require("@awayjs/stage/lib/image/GL_RenderImage2D");
var GL_RenderImageCube_1 = require("@awayjs/stage/lib/image/GL_RenderImageCube");
var GL_Sampler2D_1 = require("@awayjs/stage/lib/image/GL_Sampler2D");
var GL_SamplerCube_1 = require("@awayjs/stage/lib/image/GL_SamplerCube");
var GL_LineElements_1 = require("@awayjs/renderer/lib/elements/GL_LineElements");
var GL_TriangleElements_1 = require("@awayjs/renderer/lib/elements/GL_TriangleElements");
var GL_BillboardRenderable_1 = require("@awayjs/renderer/lib/renderables/GL_BillboardRenderable");
var GL_GraphicRenderable_1 = require("@awayjs/renderer/lib/renderables/GL_GraphicRenderable");
var GL_LineSegmentRenderable_1 = require("@awayjs/renderer/lib/renderables/GL_LineSegmentRenderable");
var GL_SkyboxRenderable_1 = require("@awayjs/renderer/lib/renderables/GL_SkyboxRenderable");
var ShaderBase_1 = require("@awayjs/renderer/lib/shaders/ShaderBase");
var GL_BasicMaterialSurface_1 = require("@awayjs/renderer/lib/surfaces/GL_BasicMaterialSurface");
var GL_SkyboxSurface_1 = require("@awayjs/renderer/lib/surfaces/GL_SkyboxSurface");
var SurfacePool_1 = require("@awayjs/renderer/lib/surfaces/SurfacePool");
var GL_Single2DTexture_1 = require("@awayjs/renderer/lib/textures/GL_Single2DTexture");
var GL_SingleCubeTexture_1 = require("@awayjs/renderer/lib/textures/GL_SingleCubeTexture");
var RendererBase_1 = require("@awayjs/renderer/lib/RendererBase");
var GL_MethodMaterialSurface_1 = require("@awayjs/materials/lib/surfaces/GL_MethodMaterialSurface");
library.Loader.enableParser(parsers.AWDParser);
library.Loader.enableParser(parsers.Max3DSParser);
library.Loader.enableParser(parsers.MD2Parser);
library.Loader.enableParser(parsers.OBJParser);
library.Loader.enableParser(parsers.FNTParser);
library.Loader.enableParser(parsers.MD5AnimParser);
library.Loader.enableParser(parsers.MD5MeshParser);
library.Loader.enableParser(parsers.Image2DParser);
library.Loader.enableParser(parsers.ImageCubeParser);
partition.PartitionBase.registerAbstraction(partition.CameraNode, display.Camera);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Sprite);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Shape);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.MovieClip);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.Billboard);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.LineSegment);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.TextField);
partition.PartitionBase.registerAbstraction(partition.EntityNode, display.TextFieldMultiRender);
partition.PartitionBase.registerAbstraction(partition.LightProbeNode, display.LightProbe);
partition.PartitionBase.registerAbstraction(partition.PointLightNode, display.PointLight);
partition.PartitionBase.registerAbstraction(partition.DirectionalLightNode, display.DirectionalLight);
partition.PartitionBase.registerAbstraction(partition.SkyboxNode, display.Skybox);
base.Stage.registerAbstraction(GL_AttributesBuffer_1.GL_AttributesBuffer, attributes.AttributesBuffer);
base.Stage.registerAbstraction(GL_RenderImage2D_1.GL_RenderImage2D, image.Image2D);
base.Stage.registerAbstraction(GL_RenderImageCube_1.GL_RenderImageCube, image.ImageCube);
base.Stage.registerAbstraction(GL_BitmapImage2D_1.GL_BitmapImage2D, image.BitmapImage2D);
base.Stage.registerAbstraction(GL_BitmapImageCube_1.GL_BitmapImageCube, image.BitmapImageCube);
base.Stage.registerAbstraction(GL_BitmapImage2D_1.GL_BitmapImage2D, image.SpecularImage2D);
base.Stage.registerAbstraction(GL_Sampler2D_1.GL_Sampler2D, image.Sampler2D);
base.Stage.registerAbstraction(GL_SamplerCube_1.GL_SamplerCube, image.SamplerCube);
SurfacePool_1.SurfacePool.registerAbstraction(GL_BasicMaterialSurface_1.GL_BasicMaterialSurface, materials.BasicMaterial);
SurfacePool_1.SurfacePool.registerAbstraction(GL_MethodMaterialSurface_1.GL_MethodMaterialSurface, materials.MethodMaterial);
SurfacePool_1.SurfacePool.registerAbstraction(GL_SkyboxSurface_1.GL_SkyboxSurface, display.Skybox);
Stage_1.Stage.registerAbstraction(GL_LineElements_1.GL_LineElements, graphics.LineElements);
Stage_1.Stage.registerAbstraction(GL_TriangleElements_1.GL_TriangleElements, graphics.TriangleElements);
ShaderBase_1.ShaderBase.registerAbstraction(GL_Single2DTexture_1.GL_Single2DTexture, textures.Single2DTexture);
ShaderBase_1.ShaderBase.registerAbstraction(GL_SingleCubeTexture_1.GL_SingleCubeTexture, textures.SingleCubeTexture);
RendererBase_1.RendererBase.registerAbstraction(GL_BillboardRenderable_1.GL_BillboardRenderable, display.Billboard);
RendererBase_1.RendererBase.registerAbstraction(GL_LineSegmentRenderable_1.GL_LineSegmentRenderable, display.LineSegment);
RendererBase_1.RendererBase.registerAbstraction(GL_GraphicRenderable_1.GL_GraphicRenderable, graphics.Graphic);
RendererBase_1.RendererBase.registerAbstraction(GL_SkyboxRenderable_1.GL_SkyboxRenderable, display.Skybox);
__export(require("./lib/adapters"));
__export(require("./lib/animators"));
__export(require("./lib/attributes"));
__export(require("./lib/base"));
__export(require("./lib/bounds"));
__export(require("./lib/controllers"));
__export(require("./lib/display"));
__export(require("./lib/draw"));
__export(require("./lib/errors"));
__export(require("./lib/events"));
__export(require("./lib/geom"));
__export(require("./lib/graphics"));
__export(require("./lib/image"));
__export(require("./lib/library"));
__export(require("./lib/managers"));
__export(require("./lib/materials"));
__export(require("./lib/net"));
__export(require("./lib/parsers"));
__export(require("./lib/partition"));
__export(require("./lib/pick"));
__export(require("./lib/prefabs"));
__export(require("./lib/projections"));
__export(require("./lib/shaders"));
__export(require("./lib/text"));
__export(require("./lib/textures"));
__export(require("./lib/tools"));
__export(require("./lib/ui"));
__export(require("./lib/utils"));
var View_1 = require("@awayjs/display/lib/View");
exports.View = View_1.View;
var DefaultRenderer_1 = require("@awayjs/renderer/lib/DefaultRenderer");
exports.DefaultRenderer = DefaultRenderer_1.DefaultRenderer;
